name: deploy-marketing

on: 
  push: 
    branches:
      - main
    paths:
      - 'packages/marketing/**'

defaults:
  # change into the directory
  run: 
    working-directory: packages/marketing

jobs: 
  build:
    runs-on: ubuntu-18.04

    steps: 
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: ls 
      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}